#vim:setlocal foldmethod = marker
[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_i = 1
hook_source = '''
source ~/.config/nvim/rc/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neco-syntax'
on_source = ['deoplete.nvim']

[[plugins]]
repo = 'Shougo/neco-vim'
depends = ['deoplete.nvim']
on_ft = ['vim']

[[plugins]]
repo = 'Shougo/neosnippet'
on_source = ['deoplete.nvim']
hook_source = '''
source ~/.config/nvim/rc/plugins/neosnippet.rc.vim
'''

[[plugins]]
repo = 'ujihisa/neco-ghc'
depends = ['deoplete.nvim']
on_ft = ['haskell']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_source = ['neosnippet']

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
source ~/.config/nvim/rc/plugins/unite.rc.vim
'''

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = ['unite.vim']

[[plugins]]
repo = 'osyo-manga/unite-quickfix'
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/tabpagebuffer.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'kmnk/vim-unite-giti'
on_source = ['unite.vim']

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
on_source = ['unite.vim']

[[plugins]]
repo = 'ujihisa/unite-haskellimport'
on_ft = ['haskell']
depends = ['unite.vim']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'jade', 'css', 'scss', 'sass']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'scss']

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'marijnh/tern_for_vim'
on_ft = ['javascript']
build = 'npm install'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']

[[plugins]]
repo = 'digitaltoad/vim-jade'
on_ft = ['jade']

[[plugins]]
repo = 'ujihisa/ref-hoogle'
on_ft = ['haskell']

[[plugins]]
repo = 'itchyny/vim-haskell-indent'
on_ft = ['haskell']

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = ['haskell']

[[plugins]]
repo = 'LaTeX-Box-Team/LaTeX-Box'
on_ft = ['tex', 'latex']
hook_source = '''
source ~/.config/nvim/rc/plugins/latexbox.rc.vim
'''

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = ['scala']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
